In [1]:
import pandas as pd;
import numpy as np;

# **Pandas Series**

In [2]:
labels = ["a", "b", "c"];
          
li = [10, 20, 30];

arr = np.array([10, 20, 30]);

dic = { "a" : 10, "b" : 20, "c" : 30 };

In [3]:
pd.Series(li) # Series Creates A Single Column With Automatic Index Label

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(li, index=labels) # Can Set With Custom Labels Also

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr, index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(dic) # Creates Series With Using Dictionary Keys As Index labels

a    10
b    20
c    30
dtype: int64

# **Pandas DataFrames**

In [7]:
data = {
    "Name": ["Ahmed", "Asmir", "Jad", "Emmett"],
    "Age": [25, 39, 38, 25],
    "City": ["Karachi", "Boras", "Gothenburg", "Amsterdam"],
    "Salary": [90000, 80000, 72000, 125000]
};

df = pd.DataFrame(data);

df

     Name  Age        City  Salary
0   Ahmed   25     Karachi   90000
1   Asmir   39       Boras   80000
2     Jad   38  Gothenburg   72000
3  Emmett   25   Amsterdam  125000

In [8]:
dataList = [
    ["Ahmed", 25, "Karachi", 90000],
    ["Asmir", 39, "Boras", 80000],
    ["Jad", 38, "Gothenburg", 72000],
    ["Emmett", 25, "Amsterdam", 125000]
];

df2 = pd.DataFrame(dataList);

df2

        0   1           2       3
0   Ahmed  25     Karachi   90000
1   Asmir  39       Boras   80000
2     Jad  38  Gothenburg   72000
3  Emmett  25   Amsterdam  125000

In [9]:
columns = ["Name", "Age", "City", "Salary"]; # Add Header

df2 = pd.DataFrame(dataList, columns=columns)

df2

     Name  Age        City  Salary
0   Ahmed   25     Karachi   90000
1   Asmir   39       Boras   80000
2     Jad   38  Gothenburg   72000
3  Emmett   25   Amsterdam  125000

# **Selection & Indexing Of Columns**

In [10]:
df2["Name"]

0     Ahmed
1     Asmir
2       Jad
3    Emmett
Name: Name, dtype: str

In [11]:
df2[["Name", "City", "Salary"]]

     Name        City  Salary
0   Ahmed     Karachi   90000
1   Asmir       Boras   80000
2     Jad  Gothenburg   72000
3  Emmett   Amsterdam  125000

In [12]:
df2["Designation"] = ["CTO", "CEO", "CMO", "Music Producer"] # Create A New Column

df2 # All Given Number Of Values Must Match The Number Of Rows (No Extra No Less)

     Name  Age        City  Salary     Designation
0   Ahmed   25     Karachi   90000             CTO
1   Asmir   39       Boras   80000             CEO
2     Jad   38  Gothenburg   72000             CMO
3  Emmett   25   Amsterdam  125000  Music Producer

In [13]:
df2.drop("Age", axis = 1) # Axis Must Be Given In Remove Column Otherwise Its Throw Error

     Name        City  Salary     Designation
0   Ahmed     Karachi   90000             CTO
1   Asmir       Boras   80000             CEO
2     Jad  Gothenburg   72000             CMO
3  Emmett   Amsterdam  125000  Music Producer

In [14]:
df2 # Remove In Memory & Not Main Data

     Name  Age        City  Salary     Designation
0   Ahmed   25     Karachi   90000             CTO
1   Asmir   39       Boras   80000             CEO
2     Jad   38  Gothenburg   72000             CMO
3  Emmett   25   Amsterdam  125000  Music Producer

In [15]:
df2.drop("Age" ,axis = 1, inplace=True);

df2 # Remove In Main Data

     Name        City  Salary     Designation
0   Ahmed     Karachi   90000             CTO
1   Asmir       Boras   80000             CEO
2     Jad  Gothenburg   72000             CMO
3  Emmett   Amsterdam  125000  Music Producer

In [16]:
df2.drop(["City", "Salary"], axis = 1) # Remove Multi Columns

     Name     Designation
0   Ahmed             CTO
1   Asmir             CEO
2     Jad             CMO
3  Emmett  Music Producer

In [17]:
df2.drop(0, axis = 0) # Remove Row

     Name        City  Salary     Designation
1   Asmir       Boras   80000             CEO
2     Jad  Gothenburg   72000             CMO
3  Emmett   Amsterdam  125000  Music Producer

In [18]:
df2

     Name        City  Salary     Designation
0   Ahmed     Karachi   90000             CTO
1   Asmir       Boras   80000             CEO
2     Jad  Gothenburg   72000             CMO
3  Emmett   Amsterdam  125000  Music Producer

In [19]:
df2.loc[3] # Select Row (Given Index Number)

Name                   Emmett
City                Amsterdam
Salary                 125000
Designation    Music Producer
Name: 3, dtype: object

In [20]:
df2.loc[[1, 2]]

    Name        City  Salary Designation
1  Asmir       Boras   80000         CEO
2    Jad  Gothenburg   72000         CMO

In [21]:
df2.iloc[3]

Name                   Emmett
City                Amsterdam
Salary                 125000
Designation    Music Producer
Name: 3, dtype: object

In [22]:
df2.iloc[[1, 2, 3]]

     Name        City  Salary     Designation
1   Asmir       Boras   80000             CEO
2     Jad  Gothenburg   72000             CMO
3  Emmett   Amsterdam  125000  Music Producer

# **Selecting Subsets Of Rows & Columns**

In [23]:
df2.loc[[0, 3]]

     Name       City  Salary     Designation
0   Ahmed    Karachi   90000             CTO
3  Emmett  Amsterdam  125000  Music Producer

In [24]:
df2.loc[0 : 3 : 3] # Slice

     Name       City  Salary     Designation
0   Ahmed    Karachi   90000             CTO
3  Emmett  Amsterdam  125000  Music Producer

In [25]:
df2.loc[[0, 3]][["Name", "City", "Salary"]]

     Name       City  Salary
0   Ahmed    Karachi   90000
3  Emmett  Amsterdam  125000

In [26]:
df2.loc[[1, 2]][["Name", "City", "Designation"]]

    Name        City Designation
1  Asmir       Boras         CEO
2    Jad  Gothenburg         CMO

# **Conditional Selection**

In [27]:
df2

     Name        City  Salary     Designation
0   Ahmed     Karachi   90000             CTO
1   Asmir       Boras   80000             CEO
2     Jad  Gothenburg   72000             CMO
3  Emmett   Amsterdam  125000  Music Producer

In [28]:
df2["Country"] = ["Pakistan", "Sweden", "Sweden", "Netherlands"];

df2

     Name        City  Salary     Designation      Country
0   Ahmed     Karachi   90000             CTO     Pakistan
1   Asmir       Boras   80000             CEO       Sweden
2     Jad  Gothenburg   72000             CMO       Sweden
3  Emmett   Amsterdam  125000  Music Producer  Netherlands

In [29]:
df2["Country"] == "Sweden"

0    False
1     True
2     True
3    False
Name: Country, dtype: bool

In [30]:
df2[df2["Country"] == "Sweden"]

    Name        City  Salary Designation Country
1  Asmir       Boras   80000         CEO  Sweden
2    Jad  Gothenburg   72000         CMO  Sweden

In [31]:
df2[df2["Salary"] > 75000]

     Name       City  Salary     Designation      Country
0   Ahmed    Karachi   90000             CTO     Pakistan
1   Asmir      Boras   80000             CEO       Sweden
3  Emmett  Amsterdam  125000  Music Producer  Netherlands

In [32]:
df2[(df2["Salary"] > 75000) & (df2["Country"] == "Sweden")]

    Name   City  Salary Designation Country
1  Asmir  Boras   80000         CEO  Sweden

In [33]:
df2[(df2["Salary"] > 75000) | (df2["City"] == "Karachi")]

     Name       City  Salary     Designation      Country
0   Ahmed    Karachi   90000             CTO     Pakistan
1   Asmir      Boras   80000             CEO       Sweden
3  Emmett  Amsterdam  125000  Music Producer  Netherlands

In [34]:
df2[(df2["Salary"] > 85000) | (df2["Country"] == "Sweden")]

     Name        City  Salary     Designation      Country
0   Ahmed     Karachi   90000             CTO     Pakistan
1   Asmir       Boras   80000             CEO       Sweden
2     Jad  Gothenburg   72000             CMO       Sweden
3  Emmett   Amsterdam  125000  Music Producer  Netherlands

# **Missing Data**

In [35]:
data = {
    "A": [1, 2, np.nan, 4, 5],
    "B": [1, 2, 3, 4, 5],
    "C": [1, 2, 3, np.nan, np.nan],
    "D": [1, np.nan, np.nan, np.nan, 5]
};

df3 = pd.DataFrame(data);

In [36]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [37]:
df3.isna() # Finding Missing Data (Null Values)

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [38]:
df3.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [39]:
df3.isna().any() # Check Column All Values Is Null

A     True
B    False
C     True
D     True
dtype: bool

In [40]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [41]:
df3.dropna() # Remove Null Values In Row

     A  B    C    D
0  1.0  1  1.0  1.0

In [42]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [43]:
df3.dropna(thresh = 3) # Atleast 3 Non-Null Values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [44]:
df3.dropna(thresh = 1) # Atleast 1 Non-Null Value

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [45]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [46]:
df3.fillna(0) # Filling Missing Data In Null Values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [47]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [48]:
values = { "A" : 0, "B" : 100, "C" : 300, "D" : 400 };

df3.fillna(value = values) # It Work In Columns

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [49]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [53]:
df3.fillna(df3.mean()) # Fill Missing Values With Column Mean.

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0